spring.data.mongodb.uri=mongodb://localhost:27017/recipedb
spring.data.mongodb.username=yourUser
spring.data.mongodb.password=yourPassword

# DevTools - hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true