/*
 * This source file was generated by the Gradle 'init' task
 */
package org.recipes

class App {
		val greeting: String
				get() {
						return "XAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAaaaaaaaaaaaa"
				}
}

fun main() {
		println(App().greeting)
}
